### ISSUE TITLE
Integrate with Flutter

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [opendroneid/receiver-android#100]
Hello Author,

Thank you for this essential utility.

How can I embed this utility into the Flutter project?

**Comment by friissoren** [comment]
I am not familiar with Flutter. 

I believe the [drone-scanner](https://github.com/dronetag/drone-scanner) application is utilizing that system?

**Comment by Rashesh-Bosamiya** [comment]
thank you for response.

The reference you have given to me.

I will deep dive into that, actually that's what I am looking for.

you can close this issue.

Thank you again,
Rashesh
