### ISSUE TITLE
WiFi Scanning frequency

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [opendroneid/receiver-android#101]
Thank you for providing this utility.
It is very useful that it offers both Bluetooth and Wi-Fi scanning methods to capture drone signals. However, I have noticed that the frequency of the Wi-Fi signal is lower compared to Bluetooth. This results in a lower refresh rate for location information when using Wi-Fi scanning, while Bluetooth is working fine and providing location information more frequently.

I am interested in learning how to adjust the Wi-Fi frequency to increase the frequency of location updates. Could you please provide guidance on how to do so?

Thank you,
Rashesh

**Comment by friissoren** [comment]
Beyond disabling the Wi-Fi throttling, there isn't really much that can be done about that. It is known that the update rate of the Wi-Fi beacon transmission method is significantly less than the update rate of Bluetooth:
https://github.com/opendroneid/receiver-android#wifi-beacon
