### ISSUE TITLE
security issue:fake remote id message

### ISSUE THREAD

**Issue by czbxzm** [opendroneid/receiver-android#106]
people can use transmitter broadcast customized fake remote id easily.This will cause false drone swarms to show up on the app.Will this be fixed in the future?

**Comment by friissoren** [comment]
It  is not possible to prevent this from the perspective of the application. Any transmitter that sends out signals that are compliant with the drone ID standards will be picked up and shown.

The current drone ID standards do not have any form of security/authentication built in. The IETF DRIP working group have work in progress to propose methods for adding this:
https://datatracker.ietf.org/wg/drip/about/

**Comment by czbxzm** [comment]
谢谢，您的邮件梁子益已收到祝好!
