### ISSUE TITLE
Smartwatch list that support BLE 5.0+ feature (Coded Phy)

### ISSUE THREAD

**Issue by s3ni0r** [opendroneid/receiver-android#107]
Do you know of any smartwatches that support BLE Coded Phy? how to check the feature support directly on the watch ? i assume that galaxy watch should support it, as the S10 and up samsung smartphones does support all the BLE 5.0 features, but can't confirm.

**Comment by friissoren** [comment]
Sorry, I have no idea. The only thing I can think of is to build your own little test application and then read out the values of these two feature flags:
https://github.com/opendroneid/receiver-android/blob/master/Android/app/src/main/java/org/opendroneid/android/bluetooth/BluetoothScanner.java#L130

I don't know if Android for smartwatches are that similar to Android phones that this method would be reliable though?
