### ISSUE TITLE
Windows Laptop Compatibility.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [opendroneid/receiver-android#109]
Is there any way to achieve similar functionality on the Windows laptop platform? Perhaps by utilizing other services or external devices? I kindly request your assistance in finding a workaround to make this feature work on a Windows laptop.

**Comment by friissoren** [comment]
The only drone ID receiver functionality that I can think of right now that would work on Windows, is the Wireshark dissector:
https://github.com/opendroneid/wireshark-dissector

That might not be what you are looking for though. 

There might be a possibility to run Android apps on Windows (?) but I guess your Googling skills would be equal to mine for figuring that out. Whether things like Bluetooth and WiFi HW access in such a simulator environment would be sufficiently functioning to actually pick up the signals, I don't know.

The known receiver implementations are listed here:
https://github.com/opendroneid/opendroneid-core-c#receiver-examples
