### ISSUE TITLE
Is there any released apk files available for download? 

### ISSUE THREAD

**Issue by lida2003** [opendroneid/receiver-android#116]
Is there any released apk files available for download? 

Or any nightly build avaliable for test?

**Comment by friissoren** [comment]
Only the one on the Google play store:
https://play.google.com/store/search?q=opendroneid&c=apps&hl=en&gl=US

**Comment by lida2003** [comment]
> Only the one on the Google play store: https://play.google.com/store/search?q=opendroneid&c=apps&hl=en&gl=US

Is there any one can help to get apk file? I can't connect google play store.
