### ISSUE TITLE
Downloading Flight track

### ISSUE THREAD

**Issue by LtDan47** [opendroneid/receiver-android#119]
Is there a way to download the flight track?

**Comment by friissoren** [comment]
All data received by the app is stored to a csv file. If you look in the menu, there is a "show log location" option.

It is possible to connect the phone to a PC, copy that csv file and import it to Excel. That would let you extract the GPS coordinates  for further processing/plotting.

**Comment by LtDan47** [comment]
This is what I got: Loggingto/storage/emulated/0/Android/data/org.opendroneid.android_osm/fileslog_motog power (2022) _moto g power_(2022)_2024-02-15_18-06-26.573.csv, that was yesterday and today: 2024-02-16 14-37-41.547.csv For the life of me I have search every cache and file on my phone and for some reason it is not there. Oh Well
