### ISSUE TITLE
Add a tag and release for version 2.0

### ISSUE THREAD

**Issue by janusw** [opendroneid/receiver-android#21]
Apparently version 2.0 was released on December 7 (f9dc8ecf757d91006a718fefc7a366a4a30d6b73), but it's still missing a tag and a release in the github project. Looking at the starting page and the [releases page](https://github.com/opendroneid/receiver-android/releases), it looks like the latest release is 1.9.0, which is very old by now.

Also it would be nice if a short description could be added in the project's "About" field. Currently it just says: `No description, website, or topics provided.`
Might be sufficient to just use `OpenDroneID Android receiver application`, maybe with a link to http://www.opendroneid.org?

**Comment by friissoren** [comment]
Good points. Fixed now.
