### ISSUE TITLE
Unable to get the google_maps_api working

### ISSUE THREAD

**Issue by DarthPlasma** [opendroneid/receiver-android#42]
I correctly inserted the api key generated on google maps platform and correcly compiled the app in release variant with self-signed key but after many tries I couldn't succeed and the map view is not working. I anso tried to restrict the api only to org.opendroneid.android with a SHA1 generated with keytool using the key i use to sign the application without success.

**Comment by friissoren** [comment]
I assume you are inserting the key here:
https://github.com/opendroneid/receiver-android/blob/master/Android/app/src/main/res/values/google_maps_api.xml#L19

There really shouldn't be anything else to it.

I have never tried to make a release version of the application. Try to build the default debug variant first and see if that makes any difference?

Maybe you can check that the key you have obtained from the Google services really is valid? It consists of 39 characters and must start with AIza.

Check also the debug logs when the application is starting up. Maybe there is a hint there?

**Comment by DarthPlasma** [comment]
> I assume you are inserting the key here: https://github.com/opendroneid/receiver-android/blob/master/Android/app/src/main/res/values/google_maps_api.xml#L19
> 
> There really shouldn't be anything else to it.
> 
> I have never tried to make a release version of the application. Try to build the default debug variant first and see if that makes any difference?
> 
> Maybe you can check that the key you have obtained from the Google services really is valid? It consists of 39 characters and must start with AIza.
> 
> Check also the debug logs when the application is starting up. Maybe there is a hint there?

I actually started over with the creation of a new project on the google developement platform and generated an new key, restricting it with the SHA1 generated by keytool and org.opendroneid.android as app name. Added the key to the proper file and now it seems to work. Probably a google maps issue. Now i am gonna test all my DJI drones to see if the "remote identification" is active on older drones
Even if the key is restricted only to the app, it should not be distributed, this is right?

I think this issue can be closed.

**Comment by friissoren** [comment]
> Even if the key is restricted only to the app, it should not be distributed, this is right?
Correct. The key is your personal one that can be used to track the amount of Google Maps activity that you have. Don't share the key unless you intend to.
