### ISSUE TITLE
List of transmitter devices

### ISSUE THREAD

**Issue by janusw** [opendroneid/receiver-android#52]
Since this repo has a very nice and useful list of supported smartphones that are capable of receiving DRI signals, one could also think about doing the same for the transmitter side. I could imagine a list of DRI-capable transmitter devices, including the supported transport types (BLE 4/5, WiFi Beacon and NAN), covering at least these two categories:
* actual drones (UAV) that support DRI out of the box
* add-on devices that can be attached to a UAV

Possibly one could also include further categories, like dev kits / boards (e.g. ESP32-based) or generic BLE/WiFi hardware with a suitable transmitter implementation.

I guess this sort of list would be quite useful for people interested in DRI technology and could help giving an overview of possible transmitters. I could certainly contribute a few.

The list could either be hosted in this repo, or somewhere else in the opendroneid org.

Any thoughts or feedback on this idea?

**Comment by friissoren** [comment]
This is a nice idea and I wouldn't object to hosting the list here. However, at the moment I wouldn't really know where to get this information from. I don't know if any drones at all are yet broadcasting DRI data. It isn't mandatory yet, in any region, to broadcast this (as far as I know?).

Currently I have spotted these add-on modules via random internet searches. There probably are more:
- https://dronetag.cz/en/products/mini/
- https://www.aerobits.pl/product/idme/
- https://www.involi.com/products/leman-drone-tracker

About HW, there are a lot of Wi-Fi and Bluetooth chips out there that theoretically can support DRI but I am not really aware of any open-source broadcast implementations for any of them, beyond what can be found in the opendroneid Github repositories already. I had plans to get something done for the TI CC2640 and possibly also the nrf52840 but never found the time for that.

**Comment by janusw** [comment]
> This is a nice idea and I wouldn't object to hosting the list here. However, at the moment I wouldn't really know where to get this information from.

As for the phones: Harvest the wisdom of the masses! 🤣

You need someone with access the the device, get him to try it with the ODID app and report the results. The more people you have doing this, the more complete the list will become. 😃 

> I don't know if any drones at all are yet broadcasting DRI data. It isn't mandatory yet, in any region, to broadcast this (as far as I know?).

Yes, to my knowledge it is not mandatory anywhere yet (maybe apart from France, which might have some special rules and special protocols?).

The only drone for which I have verified myself that it supports DRI is the Parrot Anafi, in fact.

There are rumors across the web that the DJI Mavic 3 does it as well, but I couldn't get my hands on one to verify it yet.


> Currently I have spotted these add-on modules via random internet searches. There probably are more:
> 
>     * https://dronetag.cz/en/products/mini/
> 
>     * https://www.aerobits.pl/product/idme/
> 
>     * https://www.involi.com/products/leman-drone-tracker

Good starting point for a list. I was aware of the first two, but not the last one.

> About HW, there are a lot of Wi-Fi and Bluetooth chips out there that theoretically can support DRI but I am not really aware of any open-source broadcast implementations for any of them, beyond what can be found in the opendroneid Github repositories already. I had plans to get something done for the TI CC2640 and possibly also the nrf52840 but never found the time for that.

I have only used the ESP32 implementation from https://github.com/sxjack/uav_electronic_ids. Anyway this part is kind of optional IMHO. The main part of the list would be commercially-sold consumer-ready products (drones and add-ons), but mentioning some other (more dev-oriented) transmitter implementations would be a good addition.
