### ISSUE TITLE
Correct the layout of the French translation

### ISSUE THREAD

**Issue by friissoren** [opendroneid/receiver-android#72]
In the version 3.3.2 of the application that is now on the Google Playstore, I have removed the French translation because the layout of the Info view is so messed up that many of the field values can't be seen properly.
https://play.google.com/store/apps/details?id=org.opendroneid.android_osm

It would be great if someone with French language skills could shorten the various translated strings, so that the layout becomes reasonably orderly again. Then we can get this translation back into the app version on the store.

There are also some new strings that have been added that haven't been translated to French at all.

@Tissy : Maybe you would have a possibility to look at this?

![French](https://user-images.githubusercontent.com/24454658/175012232-edc6c044-498b-4038-b23b-d4a92af5d5e6.jpg)

**Comment by Tissy** [comment]
Of course, leave it with me :)

**Comment by friissoren** [comment]
Fixed by PR #95.
