### ISSUE TITLE
Can't see BLE Long Range on Samsung Galaxy S10+

### ISSUE THREAD

**Issue by mnabilurrehman** [opendroneid/receiver-android#9]
I downloaded your project and build it. I am not able to see my BLE device. But I have used NRF Connect android app it is showing the device. What could be that will be going wrong. Can you please further guide me on this.

Thanks

**Comment by friissoren** [comment]
Maybe the discussion here will help you move forward?
https://github.com/opendroneid/receiver-android/issues/7

If not, please describe in a bit more detail what exactly you are doing and I might be able to help.
