### ISSUE TITLE
Motorola G7 Support Info

### ISSUE THREAD

**Issue by WriteCodeEveryday** [opendroneid/receiver-android#92]
I don't expect anything from this, just putting data for support. 
Close this issue as soon as the data is added to the supported table.

No WifiAware, No BLE5, although Drone Scanner says it can pick up WiFi beacons.

![Screenshot_20221012-161650](https://user-images.githubusercontent.com/1066583/195439954-e477d01b-89e3-4123-9444-21586ea6f8ef.png)
![Screenshot_20221012-161606](https://user-images.githubusercontent.com/1066583/195439956-d6255811-427f-429b-9974-647c0268bb86.png)

**Comment by friissoren** [comment]
Thanks for the contribution. I added this to the list of devices.
